### ISSUE TITLE
Bug in vaahcms/Routes/frontend.php => namespace wrong

### ISSUE THREAD

**Issue by maartengithub** [webreinvent/vaahcms-ready#21]
The code says: 
'namespace'  => 'WebReinvent\VaahCms\Http\Controllers\backend'
Mind the lowercase b in 'backend'. It should be:
'namespace'  => 'WebReinvent\VaahCms\Http\Controllers\Backend' 

Now you get a 'class not found' error.

**Comment by themodernpk** [comment]
@maartengithub thanks for reporting the issue, we'll fix it soon. Feel free to raise an PR

**Comment by maartengithub** [comment]
Another one: the configured route is:
 ANY             backend/cms/menus/action/{action}
But the requested route is:
backend/cms/menus/actions/bulk-delete (mind the plural 'actions')
So deleting a menu item doesn't work

**Comment by we-vikram-wri231** [comment]
Hi @maartengithub , thank you for reporting this issue. We are currently working on it, and it will be fixed in the next release.

Thanks again!

**Comment by themodernpk** [comment]
Hi @maartengithub,

Both issues are fixed.

Thanks
